mass: [1000,2000,3000]
lambda: ["0p1","1p0"]
first_directory: ["ntuples_training"]
second_directory_2Muons: ["ntuples_training_BDT_2Muons"]
second_directory_1Muons: ["ntuples_training_BDT_1Muons"]
signal_directory: ["Signal_BDT"]
file_TMVA_1muon: ["BDT_1Muon.root"]
file_TMVA_2muon: ["BDT_2Muon.root"]
reduced_dataset_1muon: ["makePlots_datasetlists_1muons.txt"]
reduced_dataset_2muon: ["makePlots_datasetlists_2muons.txt"]
TMVA_reduced_dataset_1muon: ["makePlots_datasetlists_1muons_BDT.txt"]
TMVA_reduced_dataset_2muon: ["makePlots_datasetlists_2muons_BDT.txt"]
