mass: [1000,2000,3000]
lambda: ["0p1","1p0"]
first_directory: ["ntuples_training_data_real"]
second_directory_2Muons: ["ntuples_training_BDT_2Muons_data"]
second_directory_1Muons: ["ntuples_training_BDT_1Muons_data"]
signal_directory: ["Signal_BDT_data"]
file_TMVA_1muon: ["BDT_1Muon_noPFisp_real.root"]
file_TMVA_2muon: ["BDT_2Muon_noPFisp_real.root"]
reduced_dataset_1muon: ["makePlots_datasetlists_1muons_data.txt"]
reduced_dataset_2muon: ["makePlots_datasetlists_2muons_data.txt"]
TMVA_reduced_dataset_1muon: ["makePlots_datasetlists_1muons_BDT_data.txt"]
TMVA_reduced_dataset_2muon: ["makePlots_datasetlists_2muons_BDT_data.txt"]
