mass: [1000,2000,3000]
lambda: ["0p1","1p0"]
first_directory: ["ntuples_training_noPFisp"]
second_directory_2Muons: ["ntuples_training_BDT_2Muons_noPFisp_real"]
second_directory_1Muons: ["ntuples_training_BDT_1Muons_noPFisp_real"]
signal_directory: ["Signal_BDT_noPFisp_real"]
file_TMVA_1muon: ["BDT_1Muon_noPFisp_real.root"]
file_TMVA_2muon: ["BDT_2Muon_noPFisp_real.root"]
reduced_dataset_1muon: ["makePlots_datasetlists_1muons_noPFisp_real.txt"]
reduced_dataset_2muon: ["makePlots_datasetlists_2muons_noPFisp_real.txt"]
TMVA_reduced_dataset_1muon: ["makePlots_datasetlists_1muons_BDT_noPFisp_real.txt"]
TMVA_reduced_dataset_2muon: ["makePlots_datasetlists_2muons_BDT_noPFisp_real.txt"]
